"""Structured business facts extracted alongside the generic RAG pipeline."""

from app.structured_facts.domain import (
    BusinessScope,
    ClaimDerivation,
    ClaimProvenance,
    ClaimQualifiers,
    ClaimRelation,
    ClaimRelationType,
    CommercialScope,
    LocationScope,
    NormalizedValue,
    ProductScope,
    QualifierCompatibility,
    ScopeRelation,
    SourceAuthority,
    StructuredClaim,
    StructuredClaimRelation,
    StructuredClaimRelationEvidence,
    StructuredClaimRelationType,
    StructuredClaimResolutionAction,
    StructuredClaimReviewStatus,
    StructuredFactClaimEvidence,
    StructuredFactSnapshotEvidence,
    TemporalContext,
    TemporalRelation,
)

__all__ = [
    "BusinessScope",
    "ClaimDerivation",
    "ClaimProvenance",
    "ClaimQualifiers",
    "ClaimRelation",
    "ClaimRelationType",
    "CommercialScope",
    "LocationScope",
    "NormalizedValue",
    "ProductScope",
    "QualifierCompatibility",
    "ScopeRelation",
    "SourceAuthority",
    "StructuredClaim",
    "StructuredClaimRelation",
    "StructuredClaimRelationEvidence",
    "StructuredClaimRelationType",
    "StructuredClaimResolutionAction",
    "StructuredClaimReviewStatus",
    "StructuredFactClaimEvidence",
    "StructuredFactSnapshotEvidence",
    "TemporalContext",
    "TemporalRelation",
]
